ALTER TABLE categories DROP CONSTRAINT IF EXISTS categories_name_key;
ALTER TABLE categories ADD CONSTRAINT categories_name_key UNIQUE (name);

INSERT INTO categories (name) VALUES
('Klavitura'),
('Video karta'),
('Sichqoncha'),
('Kuller'),
('Blok pitaniya'),
('SSD & HDD'),
('Printer'),
('Monoblok'),
('Kovrik'),
('Ona plata'),
('Xeon'),
('Keys'),
('Monitor'),
('Protsessor'),
('Naushnik'),
('Aksessuarlar'),
('Operativ xotira')
ON CONFLICT (name) DO NOTHING;

INSERT INTO products (name, category_id) SELECT 'H81 Plata', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'H510 Plata', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'H610 Plata', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'B760 DDR4 Gigabyte', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'B760 DDR5 Gigabyte', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'Gigabyte Z790D DDR5', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'Gigabyte B860M GAMING WIFI6 DDR5', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'MSI PRO B650M-P DDR5', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'MSI PRO B840M-B DDR5', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'Intel i5 2400', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel i5 4440', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core i3 - 10100F, 3.60Ghz, Oem, LGA1200', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core i3-12100F', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core i3-14100F', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core i5-12400F', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core i5-13400F', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core i5-14400F', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core i5-14600KF', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core i7-13700F', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core i7-14700F', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core i7-14700KF', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core i9-14900KF', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core Ultra 5-225F', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core Ultra 5-245KF', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Intel Core Ultra 7-265KF', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 5 5500', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 5 5600', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 5 5600X', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 7 5700X', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 5 7500F', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 5 7600X', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 7 7700X', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 7 7800X3D', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 5 9600X', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 7 9800X3D', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 9 9900X', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen 9 9950X3D', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'CPU Cooler TX-910 (95*95*55mm) LGA 1150/1151/1155/1156', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'Deep Cool AG400 WH ARGB White (125*92*150mm) LGA 1700/1200/1151/1150/1155', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'Deep Cool AG620 (129*136*157mm) LGA 1700/1200/1151/1150/1155', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'Deep Cool AK620 (129*138*160mm) LGA 1700/1200/1151/1150/1155', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'Cpu Cooler G20 plus Aura RGB (128*92*66mm) LGA 1200-1700', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'Cpu Cooler S50 RGB (120*73*153mm) LGA 1150/1155/1156/1200', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'Cpu Cooler S61 RGB (120*73*153mm) LGA 1150/1155/1156/1200', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'Cpu Cooler J 10 white RGB (120*78*155mm) LGA 1150/1155/1155/1200/1700', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'Thermalright Peerless Assasin 120 SE ARGB WH', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'Cooler Grin C40 Pro', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'Cooler Jungle C20 Pro', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'RX 580 8 GB Axle', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'GTX 1660 Super 6 GB Paladin', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'RX 550 4 GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'GTX 1050 Ti', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Axle GT730 4GB DDR3', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Peladin GTX1650 4GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Peladin RTX2060 Super 8GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Peladin RTX3050 8GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'MSI RTX3050 VENTUS 2X 8GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Sapphire RX7600 8GB PULSE', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Peladin RTX5050 8GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Peladin RTX3060 12GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Peladin RTX3070 8GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Peladin RTX5060 8GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'MSI RTX5060 SHADOW 2X 8GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Zotac RTX5060 TWIN EDGE 8GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Inno3D RTX5060Ti TWIN X2 8GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'MSI RTX5060Ti VENTUS 2X OC 8GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Inno3D RTX5060Ti 16GB TWIN X2', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'MSI RTX5070 SHADOW 2X OC 12GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'ASUS RTX5070 DUAL OC 12GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'MSI RTX5070Ti VENTUS 3X OC 16GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Palit RTX5080 GAMINGPRO 16GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Gigabyte RX9060XT GAMING OC 16GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Xtech Office case 500W', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech Mini case M5', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech Mini case M7', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech Mini case M17', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case P-05 RGB (Cpu fan 1x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case P-06 RGB (Cpu fan 1x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case P-07 RGB (Cpu fan 1x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case KT-38 RGB (Cpu fan 1x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case KG-05 RGB (Cpu fan 1x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case Fan 4', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case MH-08  RGB (Cpu fan 4x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case H-18  RGB (Cpu fan 4x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case H-10  RGB (Cpu fan 1x12sm 2x20sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case C-01 BLACK  RGB (Cpu fan 4x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case TRANSFORMER X004 RGB (Cpu fan 4x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case TRANSFORMER X007 RGB (Cpu fan 6x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case AQUARIUM X08 RGB (Cpu fan 3x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case AQUARIUM X09 RGB (Cpu fan 6x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Xtech case AQUARIUM X09 RGB white (Cpu fan 6x12sm)', id FROM categories WHERE name = 'Keys';
INSERT INTO products (name, category_id) SELECT 'Jungle Leopard w650 Pro', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'Power 500W 80  CVT', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'X-Power 500W 80 plus', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'X-Power 600W 80 plus', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'X-Power 700W 80 plus', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'X-Power  800W 80 plus', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'Deep Cool PF 500W', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'Deep Cool PF 600W', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'Deep Cool PF 650W', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'Deep Cool PF 700W', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'Deep Cool PQ 750M-V3L 80plus + Gold', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'Deep Cool PQ 1000G', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'CoolerMaster NEX 500W', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'Huntkey MVP K850 80+', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'Kingston DDR3 8Gb (1600)', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'Kingston DDR3 16 (8x8)', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'Kingston DDR4 8Gb (3200)', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'Kingston DDR4 16 (8x8) Gb (3200)', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'Kingston DDR5 16Gb (5600)', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'Kingston DDR5 32 Gb (16x16) (5600)', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'Lexar DDR4 16Gb (3200)', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'Lexar DDR5 16Gb (5600)', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'Lexar Thor DDR5 32Gb (6000)', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'Kingston DDR4 32Gb (16x2) (3200)', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'SSD 128Gb', id FROM categories WHERE name = 'SSD & HDD';
INSERT INTO products (name, category_id) SELECT 'SSD 256Gb', id FROM categories WHERE name = 'SSD & HDD';
INSERT INTO products (name, category_id) SELECT 'SSD 512Gb', id FROM categories WHERE name = 'SSD & HDD';
INSERT INTO products (name, category_id) SELECT 'SSD 1TB', id FROM categories WHERE name = 'SSD & HDD';
INSERT INTO products (name, category_id) SELECT 'SSD NVMe 256Gb', id FROM categories WHERE name = 'SSD & HDD';
INSERT INTO products (name, category_id) SELECT 'SSD NVMe 512Gb', id FROM categories WHERE name = 'SSD & HDD';
INSERT INTO products (name, category_id) SELECT 'SSD NVMe 1Tb', id FROM categories WHERE name = 'SSD & HDD';
INSERT INTO products (name, category_id) SELECT 'HDD 500 GB', id FROM categories WHERE name = 'SSD & HDD';
INSERT INTO products (name, category_id) SELECT 'HDD 1 TB', id FROM categories WHERE name = 'SSD & HDD';
INSERT INTO products (name, category_id) SELECT 'Коврик 28sm*20sm', id FROM categories WHERE name = 'Kovrik';
INSERT INTO products (name, category_id) SELECT 'Коврик 70sm*30sm', id FROM categories WHERE name = 'Kovrik';
INSERT INTO products (name, category_id) SELECT 'Коврик 80sm*30sm', id FROM categories WHERE name = 'Kovrik';
INSERT INTO products (name, category_id) SELECT 'Коврик 90sm*40sm', id FROM categories WHERE name = 'Kovrik';
INSERT INTO products (name, category_id) SELECT 'Коврик 90sm*40sm', id FROM categories WHERE name = 'Kovrik';
INSERT INTO products (name, category_id) SELECT 'Bonus Gaming Klavitura va Sichqoncha', id FROM categories WHERE name = 'Aksessuarlar';
INSERT INTO products (name, category_id) SELECT 'Xtech HS-K003 (Клавиатура и мышь) беспроводной', id FROM categories WHERE name = 'Aksessuarlar';
INSERT INTO products (name, category_id) SELECT 'Metoo С20 COMBO Black (Клавиатура и мышь) беспроводной', id FROM categories WHERE name = 'Aksessuarlar';
INSERT INTO products (name, category_id) SELECT 'Metoo С20 COMBO White (Клавиатура и мышь) беспроводной', id FROM categories WHERE name = 'Aksessuarlar';
INSERT INTO products (name, category_id) SELECT 'Great Wall GW-ES701 RGB (Клавиатура) механический', id FROM categories WHERE name = 'Aksessuarlar';
INSERT INTO products (name, category_id) SELECT 'AOC GK410 RGB (Клавиатура) механический', id FROM categories WHERE name = 'Aksessuarlar';
INSERT INTO products (name, category_id) SELECT 'A4TECH X7 KX2810 (Клавиатура и мышь) проводной', id FROM categories WHERE name = 'Aksessuarlar';
INSERT INTO products (name, category_id) SELECT 'A4TECH KR-8520D (Клавиатура и мышь) проводной', id FROM categories WHERE name = 'Aksessuarlar';
INSERT INTO products (name, category_id) SELECT '22Z440 22" Flat monitor (VGA+HDMI) VA panel 100hz NEW!!!', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'IMMER 27" FLAT 200Hz', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT '7 Tech 24 FLAT IPS FHD 180HZ', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'Ziffler 24"  144 Hz', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'Ziffler 27" Curved monitor 120hz RGB', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'Ziffler 27" Curved monitor 200hz RGB', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'Ziffler 27" Flat 200hz RGB', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'Ziffler 27" Curved 300hz', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'Ziffler 27" Curved 300hz RGB', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'Keybord FreeWolf M95', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Keybord FreeWolf M75', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Kkeybord HP GK100F', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Keybord HP GK200', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Keybord Aula F87 PRO', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Keybord Vodrik VK98', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Keybord Onikuma G52', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Keybord Onikuma G69', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Kalonka Kisonli X13', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Kalonka Kisonli X11', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Kalonka Kisonli X3', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Kalonka Kisonli A707', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Kovrik 40x90', id FROM categories WHERE name = 'Kovrik';
INSERT INTO products (name, category_id) SELECT 'Mouse FreeWolf A7', id FROM categories WHERE name = 'Sichqoncha';
INSERT INTO products (name, category_id) SELECT 'Mouse Aula SC620', id FROM categories WHERE name = 'Sichqoncha';
INSERT INTO products (name, category_id) SELECT 'Mikrafon Yanmi SF777R', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Mikrafon Marvo MIC06WH', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Mikrafon Marvo MIC08BK', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Naushnik Misde G93', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Naushnik Atack Shark L30 Pro', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Naushnik Onikuma X33', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Grin KP 600w Pro 80+', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'Naushnik V10 Moradi', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Mouse Sange G130', id FROM categories WHERE name = 'Sichqoncha';
INSERT INTO products (name, category_id) SELECT 'Mouse Scorpion Mistic 40', id FROM categories WHERE name = 'Sichqoncha';
INSERT INTO products (name, category_id) SELECT 'Mouse Eweadn X23Pro', id FROM categories WHERE name = 'Sichqoncha';
INSERT INTO products (name, category_id) SELECT 'Keyboard Eweadn V102 Ultra', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Keyboard H61K', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Keyboard Eweadn F61 wired BK', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Keyboard Eweadn G98', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'Grin 650w Pro', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT '450w Blok', id FROM categories WHERE name = 'Blok pitaniya';
INSERT INTO products (name, category_id) SELECT 'DDR4 8 GB Soddim', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'DDR3 8 GB Soddim', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'Matrix 27 Dyum 240Hz', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'Immer 27 Dyum 240Hz', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'AIO Matrix 24 H61', id FROM categories WHERE name = 'Monoblok';
INSERT INTO products (name, category_id) SELECT 'AIO Matrix 24 H610', id FROM categories WHERE name = 'Monoblok';
INSERT INTO products (name, category_id) SELECT 'AIO Ziffler 27 Dyum H61', id FROM categories WHERE name = 'Monoblok';
INSERT INTO products (name, category_id) SELECT 'Metoo C20 COMBO', id FROM categories WHERE name = 'Klavitura';
INSERT INTO products (name, category_id) SELECT 'RTX 3060 12 GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Monitor MSI 25 Dyum 300Hz', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'RTX 3060 TI 8 GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'DDR4 16 GB (3600)', id FROM categories WHERE name = 'Operativ xotira';
INSERT INTO products (name, category_id) SELECT 'RTX 2060 Super 8 GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'GT 730 4 GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Cooler KF 401 Jungle Leopard', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'Printer Epson 3210', id FROM categories WHERE name = 'Printer';
INSERT INTO products (name, category_id) SELECT 'Monoblok 27 Dyum H61 Xtech', id FROM categories WHERE name = 'Monoblok';
INSERT INTO products (name, category_id) SELECT 'Xeon Komplekt E5 2682v4, x99H, DDR4 16 gb 2400mhz, Cooler S40', id FROM categories WHERE name = 'Xeon';
INSERT INTO products (name, category_id) SELECT 'B650M H', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'Logitech C270 HD webcam', id FROM categories WHERE name = 'Aksessuarlar';
INSERT INTO products (name, category_id) SELECT 'H110 Plata', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'Everel 34 Dyum 165Hz', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'i5 7700', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'H61 Plata', id FROM categories WHERE name = 'Ona plata';
INSERT INTO products (name, category_id) SELECT 'Core i5 3470', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'HP Monitor 27 Dyum 100Hz', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'MSI 27 Dyum 2K 200Hz', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'Lenovo Legion 25 dyum 320Hz', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'Kronshteyn', id FROM categories WHERE name = 'Aksessuarlar';
INSERT INTO products (name, category_id) SELECT 'MSI Monitor 27 Dyum 240Hz', id FROM categories WHERE name = 'Monitor';
INSERT INTO products (name, category_id) SELECT 'RTX 3070Ti 8 GB', id FROM categories WHERE name = 'Video karta';
INSERT INTO products (name, category_id) SELECT 'Naushnik AULA G7PRO Wireless', id FROM categories WHERE name = 'Naushnik';
INSERT INTO products (name, category_id) SELECT 'Wifi adapter', id FROM categories WHERE name = 'Aksessuarlar';
INSERT INTO products (name, category_id) SELECT 'Mouse ATK A9 Ultra', id FROM categories WHERE name = 'Sichqoncha';
INSERT INTO products (name, category_id) SELECT 'AMD Ryzen™ 7 Raphael 9700X', id FROM categories WHERE name = 'Protsessor';
INSERT INTO products (name, category_id) SELECT 'Cooler X120', id FROM categories WHERE name = 'Kuller';
INSERT INTO products (name, category_id) SELECT 'MSI 34 Dyum 180Hz', id FROM categories WHERE name = 'Monitor';
